### ISSUE TITLE
Room system

### ISSUE THREAD

**Issue by Cars-n** [Cars-n/blink#10]

**Comment by Chris-G32** [comment]
Refers to using tiles to create rooms.

**Comment by Chris-G32** [comment]
DONE: Rooms displayed to screen. This refers to the most basic first iteration of rooms. See rooms branch to verify

**Comment by Cars-n** [comment]
Reviewed and approved. Rooms can be created using a tile system.

**Comment by Awesomecorn** [comment]
Reviewed and approved. Rooms need some refinement but meet sprint criteria
