### ISSUE TITLE
pause screen

### ISSUE THREAD

**Issue by Cars-n** [Cars-n/blink#20]
when the game is being played the user should be able to freeze the current state of their game. In the menu they should have some options such as continue playing, control description menu, exit, volume slider, etc

**Comment by eHag-FRU** [comment]
Ready for review,, just backend functionality that is either finished or is ready for other items to hook up to it

**Comment by Chris-G32** [comment]
Also denied, branch does not run. This may be a me problem, cant tell

**Comment by Awesomecorn** [comment]
Reviewed, It's working for me. I assume there's design elements that can be added. But basic functionality is reviewed

**Comment by Cars-n** [comment]
Reviewed and approved. Works as expected.
