### ISSUE TITLE
design main menu

### ISSUE THREAD

**Issue by Cars-n** [Cars-n/blink#22]
Design a prototype of the overall look of the main menu.

**Criteria:**
Design a wireframe that represents what main menu could look like.

- Include a background
- Include a start button
- Include a tutorial button
- Include a controls button
- Include a quit button
- Include a logo 
- Include a title

**Comment by dsantoli** [comment]
going to create a wireframe and get background.

**Comment by dsantoli** [comment]
Adding photos of potential main menu designs to Main-Menu Branch

**Comment by Awesomecorn** [comment]
Looked at and Approved
