### ISSUE TITLE
room system rework

### ISSUE THREAD

**Issue by Chris-G32** [Cars-n/blink#34]

**Comment by Chris-G32** [comment]
Done: room system operates on large array of 160 by 90.

**Comment by Awesomecorn** [comment]
reviewed and Approved

**Comment by Cars-n** [comment]
reviewed and approved

**Comment by eHag-FRU** [comment]
Reviewed the room system. Currently there are two bigger rooms and a hallway with doors to go between the rooms. The animation and sound effects trigger at the correct time. 


The fading in and out works properly and triggers to hide the room switching.

This task is considered done and fully functioning
