### ISSUE TITLE
Movement screens that move on contact with Doors

### ISSUE THREAD

**Issue by Awesomecorn** [Cars-n/blink#38]
When player runs into door, Move camera in correct direction

**Comment by Chris-G32** [comment]
approved.

**Comment by eHag-FRU** [comment]
Reviewed the movement between rooms. Currently there are two bigger rooms and a hallway with doors to go between the rooms. The animation and sound effects trigger at the correct time.

The fading in and out works properly and triggers to hide the room switching.

This task is considered done and fully functioning
