### ISSUE TITLE
Further refine room system to only render active room.

### ISSUE THREAD

**Issue by Chris-G32** [Cars-n/blink#56]
Room system was previously working off of an array of characters where all of the tiles of the whole map were instantiated, causing lag. In order to consider this task done, A map must be able to contain many rooms, without a substantial performance impact and it must only render the currently active room.

**Comment by Chris-G32** [comment]
Branch is rooms.

**Comment by Awesomecorn** [comment]
Approved

**Comment by Cars-n** [comment]
reviewed and approved. the rendering creates a pause between the page loading and the main menu appearing. we should talk about creating an issue to make an indication for the loading on saturday.
