### ISSUE TITLE
Room creation tool: Add in tile palette to use existing tiles from game. Does not need to edit yet.

### ISSUE THREAD

**Issue by Chris-G32** [Cars-n/blink#73]
Branch: room-editor-tiles.

**Comment by Chris-G32** [comment]
Done: Tiles can be identified and selected by image to change map editor

**Comment by Cars-n** [comment]
Reviewed and approved. Works as expected. Only recommendation would be to add a mouse click function as well for when just changing one tile but still works fine without it.

**Comment by Awesomecorn** [comment]
Reviewed and approved. View window is slightly off but works other than that
